Hw 23 1
semyonich/jv-dao-service pull request #5
Opened 2021-01-19 14:34 UTC by semyonich

2021-01-19 14:45 UTC, Fedich09 approved these changes

2021-01-19 17:11 UTC, semyonich commented on src/main/java/core/basesyntax/dao/jdbc/CarDaoJdbcImpl.java
> +        } catch (SQLException e) {
let's fetch and set drivers only if carResultSet.next() == true. Also let's create Car link inside try block and add return statement here too(Warning from prev. HW)

2021-01-19 19:05 UTC, semyonich commented on src/main/java/core/basesyntax/dao/jdbc/CarDaoJdbcImpl.java
> +        } catch (SQLException e) {
done

2021-01-20 07:30 UTC, boroda4436 requested changes
There are some classes from previous HW presented. Please remove not required files from this PR

2021-01-20 08:09 UTC, semyonich commented
> There are some classes from previous HW presented. Please remove not required files from this PR

do you mean Application class ? because any other needless classes I cant find here?

2021-01-20 10:17 UTC, closed without merging